### ISSUE TITLE
Conflict between matplotlib and using python environments

### ISSUE THREAD

**Issue by fusaroli** [syncpy/SyncPy#1]
I normally use python 3, so I had to create a python 2 virtual environment for trying out syncpy.
However, this generates a conflict with Matplotlib, when trying to run the "MainWindow.py" or any example file relying on matplotlib.

This should be noted in the documentation and a workaround should be suggested (as more and more people are switching to python3). One workaround is suggested here: http://matplotlib.org/1.5.0/faq/virtualenv_faq.html

Here the log:

Traceback (most recent call last):
  File "MainWindow.py", line 50, in <module>
    from MethodSelectionWindow import MethodSelectionWindow
  File "/SyncPy/interface/sources/MethodSelectionWindow.py", line 43, in <module>
    from SynchronyMethod import SynchronyMethod
  File "/SyncPy/interface/sources/SynchronyMethod.py", line 43, in <module>
    from PlotWindow import PlotWindow
  File "/SyncPy/interface/sources/PlotWindow.py", line 41, in <module>
    import matplotlib.pyplot as plt
  File "/Users/semrf/anaconda/envs/python2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/semrf/anaconda/envs/python2/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/Users/semrf/anaconda/envs/python2/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 24, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ

**Comment by syncpy** [comment]
Hi fusaroli, thanks for your feedback, we will update the requirements & dependencies in the next version soon and add the link to address the specific bug of Matplotlib in virtual environment.
